using System;
using System.Collections.Generic;

namespace WarehouseReqs.Models
{
    public partial class Employee
    {
        public string EmpNum { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string Ssn { get; set; }
        public string Dept { get; set; }
        public string EmpType { get; set; }
        public string PayFreq { get; set; }
        public decimal? MfgRegRate { get; set; }
        public decimal? MfgOtRate { get; set; }
        public decimal? MfgDtRate { get; set; }
        public DateTime? BirthDate { get; set; }
        public string MaritalStat { get; set; }
        public DateTime? HireDate { get; set; }
        public DateTime? RaiseDate { get; set; }
        public DateTime? ReviewDate { get; set; }
        public string WcClass { get; set; }
        public DateTime? TermDate { get; set; }
        public string WageAcct { get; set; }
        public decimal? Salary { get; set; }
        public decimal? RegRate { get; set; }
        public decimal? OtRate { get; set; }
        public decimal? DtRate { get; set; }
        public byte? FwtNum { get; set; }
        public decimal? FwtDol { get; set; }
        public byte? SwtNum { get; set; }
        public decimal? SwtDol { get; set; }
        public byte? OstNum { get; set; }
        public decimal? OstDol { get; set; }
        public byte? CwtNum { get; set; }
        public decimal? CwtDol { get; set; }
        public decimal? StateCr { get; set; }
        public byte? EicCr { get; set; }
        public string StateCode { get; set; }
        public string CityCode { get; set; }
        public byte? FicaExempt { get; set; }
        public byte? FuiExempt { get; set; }
        public byte? SuiExempt { get; set; }
        public string AddFwtType { get; set; }
        public decimal? AddFwtAmt { get; set; }
        public string AddSwtType { get; set; }
        public decimal? AddSwtAmt { get; set; }
        public string AddCwtType { get; set; }
        public decimal? AddCwtAmt { get; set; }
        public decimal? VacHrDue { get; set; }
        public decimal? VacHrPd { get; set; }
        public decimal? SickHrDue { get; set; }
        public byte? Pension { get; set; }
        public decimal? InsPrem { get; set; }
        public byte? TipCr { get; set; }
        public decimal? UnionAmt { get; set; }
        public string UnionType { get; set; }
        public string UnionFreq { get; set; }
        public string UnionAcct { get; set; }
        public decimal? LoanAmt { get; set; }
        public string LoanFreq { get; set; }
        public decimal? LoanBal { get; set; }
        public decimal? GarnAmt { get; set; }
        public string GarnType { get; set; }
        public string GarnFreq { get; set; }
        public decimal? GarnBal { get; set; }
        public string DeCode1 { get; set; }
        public string DeCode2 { get; set; }
        public string DeCode3 { get; set; }
        public string DeCode4 { get; set; }
        public string DeCode5 { get; set; }
        public string DeCode6 { get; set; }
        public string DeCode7 { get; set; }
        public string DeCode8 { get; set; }
        public string DeCode9 { get; set; }
        public string DeCode10 { get; set; }
        public string DeCode11 { get; set; }
        public string DeCode12 { get; set; }
        public string DeCode13 { get; set; }
        public string DeCode14 { get; set; }
        public string DeCode15 { get; set; }
        public decimal? DeAmt1 { get; set; }
        public decimal? DeAmt2 { get; set; }
        public decimal? DeAmt3 { get; set; }
        public decimal? DeAmt4 { get; set; }
        public decimal? DeAmt5 { get; set; }
        public decimal? DeAmt6 { get; set; }
        public decimal? DeAmt7 { get; set; }
        public decimal? DeAmt8 { get; set; }
        public decimal? DeAmt9 { get; set; }
        public decimal? DeAmt10 { get; set; }
        public decimal? DeAmt11 { get; set; }
        public decimal? DeAmt12 { get; set; }
        public decimal? DeAmt13 { get; set; }
        public decimal? DeAmt14 { get; set; }
        public decimal? DeAmt15 { get; set; }
        public string DeFreq1 { get; set; }
        public string DeFreq2 { get; set; }
        public string DeFreq3 { get; set; }
        public string DeFreq4 { get; set; }
        public string DeFreq5 { get; set; }
        public string DeFreq6 { get; set; }
        public string DeFreq7 { get; set; }
        public string DeFreq8 { get; set; }
        public string DeFreq9 { get; set; }
        public string DeFreq10 { get; set; }
        public string DeFreq11 { get; set; }
        public string DeFreq12 { get; set; }
        public string DeFreq13 { get; set; }
        public string DeFreq14 { get; set; }
        public string DeFreq15 { get; set; }
        public decimal? YtdGrs { get; set; }
        public decimal? YtdFwtGrs { get; set; }
        public decimal? YtdEficaGr { get; set; }
        public decimal? YtdRficaGr { get; set; }
        public decimal? YtdFuiGrs { get; set; }
        public decimal? YtdOstGrs { get; set; }
        public decimal? YtdWcGrs { get; set; }
        public decimal? YtdSbGrs { get; set; }
        public decimal? YtdSuiGrs { get; set; }
        public decimal? YtdFica { get; set; }
        public decimal? YtdFwt { get; set; }
        public decimal? YtdEic { get; set; }
        public decimal? YtdSwt { get; set; }
        public decimal? YtdOst { get; set; }
        public decimal? YtdCwt { get; set; }
        public decimal? YtdTipCr { get; set; }
        public decimal? DeBal1 { get; set; }
        public decimal? DeBal2 { get; set; }
        public decimal? DeBal3 { get; set; }
        public decimal? DeBal4 { get; set; }
        public decimal? DeBal5 { get; set; }
        public decimal? DeBal6 { get; set; }
        public decimal? DeBal7 { get; set; }
        public decimal? DeBal8 { get; set; }
        public decimal? DeBal9 { get; set; }
        public decimal? DeBal10 { get; set; }
        public decimal? DeBal11 { get; set; }
        public decimal? DeBal12 { get; set; }
        public decimal? DeBal13 { get; set; }
        public decimal? DeBal14 { get; set; }
        public decimal? DeBal15 { get; set; }
        public string DeType1 { get; set; }
        public string DeType2 { get; set; }
        public string DeType3 { get; set; }
        public string DeType4 { get; set; }
        public string DeType5 { get; set; }
        public string DeType6 { get; set; }
        public string DeType7 { get; set; }
        public string DeType8 { get; set; }
        public string DeType9 { get; set; }
        public string DeType10 { get; set; }
        public string DeType11 { get; set; }
        public string DeType12 { get; set; }
        public string DeType13 { get; set; }
        public string DeType14 { get; set; }
        public string DeType15 { get; set; }
        public string County { get; set; }
        public string Country { get; set; }
        public decimal? CoPdIns { get; set; }
        public decimal? EmprCon { get; set; }
        public decimal? YtdCoPdIn { get; set; }
        public decimal? YtdEmprCon { get; set; }
        public string Shift { get; set; }
        public string PrFrom { get; set; }
        public string Charfld1 { get; set; }
        public string Charfld2 { get; set; }
        public string Charfld3 { get; set; }
        public decimal? Decifld1 { get; set; }
        public decimal? Decifld2 { get; set; }
        public decimal? Decifld3 { get; set; }
        public byte? Logifld { get; set; }
        public DateTime? Datefld { get; set; }
        public byte? DirDep { get; set; }
        public string IndCode { get; set; }
        public byte? LunchAuto { get; set; }
        public string RetireType { get; set; }
        public decimal? YtdEmpCon { get; set; }
        public decimal? YtdSwtGrs { get; set; }
        public decimal? YtdCwtGrs { get; set; }
        public decimal? YtdMed { get; set; }
        public decimal? YtdEmedGrs { get; set; }
        public decimal? YtdRmedGrs { get; set; }
        public string Addr1 { get; set; }
        public string Addr2 { get; set; }
        public string Addr3 { get; set; }
        public string Addr4 { get; set; }
        public string Lname { get; set; }
        public string Fname { get; set; }
        public string Mname { get; set; }
        public string Mi { get; set; }
        public string Bname { get; set; }
        public string Nickname { get; set; }
        public string Sex { get; set; }
        public byte? NoChldrn { get; set; }
        public string Spouse { get; set; }
        public string PhExt { get; set; }
        public string EthnicId { get; set; }
        public byte? Handicap { get; set; }
        public string Military { get; set; }
        public string WStatus { get; set; }
        public byte? CarUse { get; set; }
        public byte? PctUse { get; set; }
        public byte? CarAllow { get; set; }
        public decimal? CaMonth { get; set; }
        public decimal? Camileage { get; set; }
        public byte? Citizen { get; set; }
        public string Nationality { get; set; }
        public DateTime? SbDate { get; set; }
        public byte? NoDpndts { get; set; }
        public DateTime? ADate { get; set; }
        public string AppNum { get; set; }
        public short? SrvLeave { get; set; }
        public short? SrvLyoff { get; set; }
        public string WageAcctUnit1 { get; set; }
        public string WageAcctUnit2 { get; set; }
        public string WageAcctUnit3 { get; set; }
        public string WageAcctUnit4 { get; set; }
        public string UnionAcctUnit1 { get; set; }
        public string UnionAcctUnit2 { get; set; }
        public string UnionAcctUnit3 { get; set; }
        public string UnionAcctUnit4 { get; set; }
        public byte NoteExistsFlag { get; set; }
        public DateTime RecordDate { get; set; }
        public Guid RowPointer { get; set; }
        public string WorkCountryCode { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime CreateDate { get; set; }
        public byte InWorkflow { get; set; }
        public DateTime? UfCdpdate { get; set; }
        public string UfCdplevel { get; set; }
        public string UfTerminationReason { get; set; }
        public int? UfPartTime { get; set; }
        public DateTime? UfDeferralDate { get; set; }
        public DateTime? UfMatchDate { get; set; }
        public string Sname { get; set; }
        public byte[] Picture { get; set; }
        public string EmailAddr { get; set; }
        public string BusinessPhone { get; set; }
        public DateTime? UfPlanEntryDate { get; set; }
        public DateTime? UfPlanMatchDate { get; set; }
        public string UfFireEvacDept { get; set; }
    }
}
